data: {
  train_dir: /ssd_scratch/cvit/amruth.sagar/ads_non_ads/train,
  val_dir: /ssd_scratch/cvit/amruth.sagar/ads_non_ads/val,
  test_dir: /ssd_scratch/cvit/amruth.sagar/ads_non_ads/test,
  reshape_height: 224,
  reshape_width: 224,
  augment: True
}
model: {
  batch_size: 32,
  train_bs: 32,
  valid_bs: 8,
  vit_pretrained: google/vit-base-patch16-224-in21k,
  learning_rate: 0.001,
  epochs: 100,
  vit_feature_dim: 768
}
of_test: {
  num_imgs_per_cls: 10,
  do_overfit_test: True,
  batch_size: 4,
  epochs: 150
}
wandb: {
  wandb_log: True,
  project: Indic_ADS,
  entity: indicads,
  exp_name: of.test.ViT.frz.Cls.head.b4.e150.im10
}
